// Action types for creature
export const FETCH_CREATURES_START = 'FETCH_CREATURES_START';
export const FETCH_CREATURES_SUCCESS = 'FETCH_CREATURES_SUCCESS';
export const FETCH_CREATURES_ERROR = 'FETCH_CREATURES_ERROR';
export const FETCH_CREATURES_REDBOOK_SUCCESS = 'FETCH_CREATURES_REDBOOK_SUCCESS';
export const FETCH_CREATURES_REDBOOK_START = 'FETCH_CREATURES_REDBOOK_START';
export const DELETE_CREATURE_SUCCESS = 'DELETE_CREATURE_SUCCESS';
export const DELETE_CREATURE_ERROR = 'DELETE_CREATURE_ERROR';

// Action for fetch one creature
export const FETCH_CREATURES_BY_ID = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_START = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_SUCCESS = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_ERROR = 'FETCH_CREATURES_BY_ID';


// Action types for filter data
export const FETCH_FILTER_DATA = 'FETCH_FILTER_DATA';
export const FETCH_FILTER_DATA_START = 'FETCH_FILTER_DATA_START';
export const FETCH_FILTER_DATA_SUCCESS = 'FETCH_FILTER_DATA_SUCCESS';
export const FETCH_FILTER_DATA_ERROR = 'FETCH_FILTER_DATA_ERROR';

// Action for delete error
export const DELETE_ERROR = 'DELETE_ERROR';

// Action Fetch HasTag ID
export const FETCH_START = 'FETCH_START';
export const FETCH_HASHTAG_ID_SUCCESS = 'FETCH_HASHTAG_ID_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

//action fetch post
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';
export const CHANGE_POST_START = 'CHANGE_POST_START';
export const CHANGE_POST_SUCCESS = 'CHANGE_POST_SUCCESS';
export const CHANGE_POST_ERROR = 'CHANGE_POST_ERROR';
export const POST_END_FORM = 'POST_END_FORM';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

// Species start
export const SPECIES_START = 'SPECIES_START';
export const SPECIES_ERROR = 'SPECIES_ERROR';
export const FETCH_SPECIES_SUCCESS = 'FETCH_SPECIES_SUCCESS';
export const CREATE_SPECIES_START = 'CREATE_SPECIES_START';
export const CREATE_SPECIES_SUCCESS = 'CREATE_SPECIES_SUCCESS';
export const CREATE_SPECIES_ERROR = 'CREATE_SPECIES_ERROR';
export const DELETE_SPECIES_SUCCESS = 'DELETE_SPECIES_SUCCESS';
export const DELETE_SPECIES_ERROR = 'DELETE_SPECIES_ERROR';
export const SPECIES_END_FORM = 'SPECIES_END_FORM';
export const UPDATE_SPECIES_SUCCESS = 'UPDATE_SPECIES_SUCCESS';

// category
export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

// National parks
export const NATIONAL_PARKS_START = "NATIONAL_PARKS_START";
export const NATIONAL_PARKS_ERROR = "NATIONAL_PARKS_ERROR";
export const FETCH_NP_BY_ID_SUCCES = "FETCH_NP_BY_ID_SUCCES";
export const FETCH_NP_COORDS_SUCCESS = 'FETCH_NP_COORDS_SUCCESS';

// AUTHOR
export const AUTHOR_START = "AUTHOR_START";
export const AUTHOR_ERROR = "AUTHOR_ERROR";
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";

// Latin dic
export const LATIN_DIC_START = 'LATIN_DIC_START';
export const LATIN_DIC_ERROR = 'LATIN_DIC_ERROR';
export const SEARCH_LATIN_DIC_SUCCESS = 'LATIN_DIC_SUCCESS';

// Login 
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';

// admin
export const EDIT_CREATURE_START = 'EDIT_CREATURE_START';

// group
export const GROUP_START = 'GROUP_START';
export const GROUP_ERROR = 'GROUP_ERROR';
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';
export const GROUPS_END_FORM = 'GROUPS_END_FORM';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
//
export const ORDER_START = 'ORDER_START';
export const ORDER_ERROR = 'ORDER_ERROR';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const ORDERS_END_FORM = 'ORDERS_END_FORM';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

// families
export const FAMILIES_START = 'FAMILIES_START';
export const FAMILIES_ERROR = 'FAMILIES_ERROR';
export const FETCH_FAMILIES_SUCCESS = 'FETCH_FAMILIES_SUCCESS';
export const CREATE_FAMILY_SUCCESS = 'CREATE_FAMILY_SUCCESS';
export const CREATE_FAMILY_ERROR = 'CREATE_FAMILY_ERROR';
export const FAMILIES_END_FORM = 'FAMILIES_END_FORM';
export const DELETE_FAMILY_SUCCESS = 'DELETE_FAMILY_SUCCESS';
export const DELETE_FAMILY_ERROR = 'DELETE_FAMILY_ERROR';
export const UPDATE_FAMILY_SUCCESS = 'UPDATE_FAMILY_SUCCESS';

// Asset 
export const ASSETS_START = 'ASSETS_START';
export const FETCH_ASSETS_SUCCESS = 'FETCH_ASSETS_SUCCESS';
export const ASSET_ERROR = 'ASSET_ERROR';
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS';
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';

//User
export const USER_START =  'USER_START';
export const USER_ERROR = 'USER_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

//Wood
export const WOOD_START  = "WOOD_START";
export const WOOD_ERROR = "WOOD_ERROR";
export const FETCH_WOOD_SUCCESS = "FETCH_WOOD_SUCCESS";